# Generated by Django 5.1.7 on 2025-03-20 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='annual_leave_balance',
            field=models.DecimalField(decimal_places=1, default=21.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='employee',
            name='sick_leave_balance',
            field=models.DecimalField(decimal_places=1, default=10.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('Annual', 'Annual Leave'), ('Sick', 'Sick Leave'), ('Other', 'Other')], default='Annual', max_length=20),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
